Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using NiceAdmin.Models;
using System.Data.SqlClient;
using System.Data;
using System.Collections.Specialized;
using OfficeOpenXml;

namespace NiceAdmin.Controllers
{
    public class BillController : Controller
    {
        private IConfiguration configuration;

        public BillController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult Bills()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection sqlConnection = new SqlConnection(connectionString);
            sqlConnection.Open();
            SqlCommand sqlCommand = sqlConnection.CreateCommand();
            sqlCommand.CommandType = CommandType.StoredProcedure;
            sqlCommand.CommandText = "PR_Bills_SelectAll";
            SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return View(dataTable);
        }

        public IActionResult BillDelete(int BillID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_Bills_DeleteByPK";
                sqlCommand.Parameters.Add("@BillID", SqlDbType.Int).Value = BillID;
                sqlCommand.ExecuteNonQuery();
                return RedirectToAction("Bills");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString);
                return RedirectToAction("Bills");
            }
        }

        public IActionResult BillSave(BillModel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (model.BillID == 0)
                {
                    command.CommandText = "PR_Bills_Insert";
                }
                else
                {
                    command.CommandText = "PR_Bills_UpdateByPK";
                    command.Parameters.Add("@BillID", SqlDbType.Int).Value = model.BillID;
                }
                command.Parameters.Add("@BillNumber", SqlDbType.VarChar).Value = model.BillNumber;
                command.Parameters.Add("@BillDate", SqlDbType.DateTime).Value = model.BillDate;
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = model.OrderID;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = model.TotalAmount;
                command.Parameters.Add("@Discount", SqlDbType.Decimal).Value = model.Discount;
                command.Parameters.Add("@NetAmount", SqlDbType.Decimal).Value = model.NetAmount;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = model.UserID;
                command.ExecuteNonQuery();
                return RedirectToAction("Bills");
            }

            return View("BillsForm", model);
        }
        public IActionResult BillsForm(int BillID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection sqlConnection1 = new SqlConnection(connectionString);
            sqlConnection1.Open();
            SqlCommand command1 = sqlConnection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }

            ViewBag.Users = userList;

            SqlConnection sqlConnection2 = new SqlConnection(connectionString);
            sqlConnection2.Open();
            SqlCommand command2 = sqlConnection1.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_Orders_DropDown";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow data in dataTable2.Rows)
            {
                OrderDropDownModel orderDropDownModel = new OrderDropDownModel();
                orderDropDownModel.OrderID = Convert.ToInt32(data["OrderID"]);
                orderDropDownModel.OrderCode = data["OrderCode"].ToString();
                orderList.Add(orderDropDownModel);
            }

            ViewBag.Orders = orderList;

            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_Bills_SelectByPK";
            command.Parameters.AddWithValue("@BillID", BillID);
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            BillModel billModel = new BillModel();
            foreach (DataRow dataRow in table.Rows)
            {
                billModel.BillNumber = @dataRow["BillNumber"].ToString();
                billModel.BillDate = Convert.ToDateTime(@dataRow["BillDate"]);
                billModel.OrderID = Convert.ToInt32(@dataRow["OrderID"]);
                billModel.TotalAmount = Convert.ToDecimal(@dataRow["TotalAmount"]);
                billModel.Discount = Convert.ToDecimal(@dataRow["Discount"]);
                billModel.NetAmount = Convert.ToDecimal(@dataRow["NetAmount"]);
                billModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }

            return View("BillsForm",billModel);
        }

        public IActionResult ExportToExcel()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (var sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                using (var sqlCommand = sqlConnection.CreateCommand())
                {
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.CommandText = "PR_Bills_SelectAll";
                    using (var sqlDataReader = sqlCommand.ExecuteReader())
                    {
                        var dataTable = new DataTable();
                        dataTable.Load(sqlDataReader);

                        using (var package = new ExcelPackage())
                        {
                            var worksheet = package.Workbook.Worksheets.Add("Users");
                            worksheet.Cells["A1"].LoadFromDataTable(dataTable, true);

                            var stream = new MemoryStream();
                            package.SaveAs(stream);
                            stream.Position = 0;

                            var fileName = "Bills.xlsx";
                            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                        }
                    }
                }
            }
        }
    }
}

Views/Bill/Bills.cshtml
@model DataTable
@using System.Data


<main id="main" class="main">
    <div class="card">
        <div class="card-body">

            <div class="d-flex justify-content-between align-items-center">
                <h5 class="card-title">Bill Detail</h5>
                <button class="btn btn-primary">
                    <a class="text-white" asp-controller="Bill" asp-action="BillsForm">
                        <i class="bi bi-plus"></i><span>Add Bills</span>
                    </a>
                </button>
                <button class="btn btn-success">
                    <a class="text-white" asp-controller="Bill" asp-action="ExportToExcel">
                        <i class="bi bi-file-earmark-excel"></i><span>Export to Excel</span>
                    </a>
                </button>
            </div>

            <h6 class="text-danger">@TempData["ErrorMessage"]</h6>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">BillID</th>
                        <th scope="col">BillNumber</th>
                        <th scope="col">BillDate</th>
                        <th scope="col">OrderID</th>
                        <th scope="col">TotalAmount</th>
                        <th scope="col">Discount</th>
                        <th scope="col">NetAmount</th>
                        <th scope="col">UserID</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DataRow dataRow in Model.Rows)
                    {
                        <tr>
                            <th scope="row">@dataRow["BillID"]</th>
                            <td>@dataRow["BillNumber"]</td>
                            <td>@dataRow["BillDate"]</td>
                            <td>@dataRow["OrderCode"]</td>
                            <td>@dataRow["TotalAmount"]</td>
                            <td>@dataRow["Discount"]</td>
                            <td>@dataRow["NetAmount"]</td>
                            <td>@dataRow["UserName"]</td>
                            <td>
                                <div class="d-flex align-items-stretch">
                                    <button class="btn" onclick="confirmDelete(@dataRow["BillID"])">
                                        <i class="fas fa-trash-alt" style="color: red;"></i>
                                    </button>
                                    <a asp-controller="Bill" asp-action="BillsForm" asp-route-BillID="@Convert.ToInt32(@dataRow["BillID"])" title="Edit">
                                        <button class="btn">
                                            <i class="fas fa-edit" style="color: greenyellow;"></i>
                                        </button>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</main>

<script>
    function confirmDelete(billID) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                // Submit the form via AJAX or a redirect
                window.location.href = '@Url.Action("BillDelete", "Bill")?BillID=' + billID;
            }
        })
    }
</script>

Views/Bill/BillsForm.cshtml
@model NiceAdmin.Models.BillModel

@{
    ViewData["Title"] = "Bill Form";
}

<main id="main" class="main">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Bills</h5>

            <h1>Bill Form</h1><br />
            <form asp-controller="Bill" asp-action="BillSave" method="post">
                <input type="hidden" asp-for="BillID" />
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="row mb-3">
                    <label for="BillNumber" class="col-sm-2 col-form-label"><span class="text-danger">*</span>Bill Number</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" asp-for="BillNumber" />
                        <span asp-validation-for="BillNumber" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="BillDate" class="col-sm-2 col-form-label"><span class="text-danger">*</span>Bill Date</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" asp-for="BillDate" />
                        <span asp-validation-for="BillDate" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="OrderID" class="col-sm-2 col-form-label"><span class="text-danger">*</span>Order ID</label>
                    <div class="col-sm-10">
                        <select class="form-control" asp-for="OrderID" asp-items="@(new SelectList(ViewBag.Orders, "OrderID", "OrderCode"))">
                            <option value="">Select OrderCode</option>
                        </select>
                        <span asp-validation-for="OrderID" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="TotalAmount" class="col-sm-2 col-form-label"><span class="text-danger">*</span>Total Amount</label>
                    <div class="col-sm-10">
                        <input type="number" step="0.01" class="form-control" asp-for="TotalAmount" />
                        <span asp-validation-for="TotalAmount" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="Discount" class="col-sm-2 col-form-label">Discount</label>
                    <div class="col-sm-10">
                        <input type="number" step="0.01" class="form-control" asp-for="Discount" />
                        <span asp-validation-for="Discount" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="NetAmount" class="col-sm-2 col-form-label"><span class="text-danger">*</span>Net Amount</label>
                    <div class="col-sm-10">
                        <input type="number" step="0.01" class="form-control" asp-for="NetAmount" />
                        <span asp-validation-for="NetAmount" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="UserID" class="col-sm-2 col-form-label"><span class="text-danger">*</span>User ID</label>
                    <div class="col-sm-10">
                        <select class="form-control" asp-for="UserID" asp-items="@(new SelectList(ViewBag.Users, "UserID", "UserName"))">
                            <option value="">Select User</option>
                        </select>
                        <span asp-validation-for="UserID" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a asp-controller="Bill" asp-action="Bills" class="btn btn-secondary">Back</a>
                    </div>
                </div>
            </form>

            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }
        </div>
    </div>
</main>